language: python
python:
  - "3.4"
# command to run tests
script: 
        - git clone https://github.com/garridev/agora-results.git
        - cd agora-results/
        - python setup.py install
        - wget http://filebin.ca/2TMEkuB1rjNi/tally.tar.gz
        - python agora-results -t tally.tar.gz -c config.json -s
        - git clone https://github.com/EGC-AgoraResultsTest/agora-results-tests.git
        - cd agora-results-tests/
        - sh install_agora_results_tests.sh
        - pyb -v
        
