language: python
python:
  - "3.4"
# command to run tests
script: 
        - git clone https://github.com/EGC-AgoraResultsTest/agora-results-tests.git
        - cd agora-results-tests/
        - rm -rf install_agora_results_tests.sh
        - wget http://pastebin.com/raw/ZiuN0BPQ
        - mv ZiuN0BPQ install_agora_results_tests.sh
        - sh install_agora_results_tests.sh
